spring:
  application:
    name: youtube-clone

  data:
    mongodb:
      host: localhost
      port: 27017
      database: youtube-clone
      auto-index-creation: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html


#AWS properties
aws:
  accessKey: AKIARV3CMNE6T354SVNS
  secretKey: 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
  region: ap-south-1

#  accessKey: <accesskey>
#  secretKey: <secretKey>
#  region: <region>

s3:
  bucket:
    name: jskool-youtube-clone