spring:
  application:
    name: youtube-clone

  data:
    mongodb:
      host: localhost
      port: 27017
      database: youtube-clone
      auto-index-creation: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: <issueUrl>
          audiences:  http://localhost:8080


# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html


logging:
  file:
    path: logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    web: error
    root: info
    sql: error


#AWS properties

#  accessKey: <accesskey>
#  secretKey: <secretKey>
#  region: <region>

s3:
  bucket:
    name: jskool-bucket

