
spring:
  application:
    name: youtube-clone
  config:
    import: "optional:configserver:http://localhost:8080"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: youtube-clone
      auto-index-creation: false


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-fdcej4517yao5gy8.uk.auth0.com/
          audiences:  http://localhost:8080/
      authorizationserver:
        endpoint:
          oidc:
            user-info-uri: https://dev-fdcej4517yao5gy8.uk.auth0.com/userinfo



# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html


logging:
  file:
    path: logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    web: error
    root: info
    sql: error


